#!/usr/bin/env ruby

BOX         = "generic/debian12"
SERVER_IP   = "192.168.171.10"
CLIENT_IP   = "192.168.171.1"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_check_update = false

  config.vm.synced_folder "./target/x86_64-unknown-linux-musl/release", "/app",
    disable: true,
    type: "rsync",
    rsync__args: ["--verbose", "--archive", "--delete", "-z"]

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.post_up_message = "vagrant ssh server (#{SERVER_IP})"
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: CLIENT_IP
    client.vm.post_up_message = "vagrant ssh client (#{CLIENT_IP})"
  end
end
